### ISSUE TITLE
ETA first release ?

### ISSUE THREAD

**Issue by fpondepeyre** [thephpleague/oauth2-server-bundle#1]
Hello,
Oh my god, you did it !
Do you have an estimate of a release date (alpha, beta, stable ?)
Thank you.

**Comment by chalasr** [comment]
Thanks for your interest @fpondepeyre.
We should get to release something in July :)

**Comment by fpondepeyre** [comment]
Thanks you, it will be an amazing bundle, good luck !

**Comment by Kravalg** [comment]
@chalasr is there any news?
