### ISSUE TITLE
Doctrine ORM 2.9 deprecated message

### ISSUE THREAD

**Issue by sdespont** [thephpleague/oauth2-server-bundle#132]
Hello,

New deprecated message after composer update in relation with Doctrine ORM 2.9

`The "Doctrine\Bundle\DoctrineBundle\DependencyInjection\Compiler\DoctrineOrmMappingsPass" class is considered final since 2.9. It may change without further notice as of its next major version. You should not extend it from "League\Bundle\OAuth2ServerBundle\DependencyInjection\CompilerPass\RegisterDoctrineOrmMappingPass".`

**Comment by haivala** [comment]
https://github.com/thephpleague/oauth2-server-bundle/issues/135

**Comment by sdespont** [comment]
@haivala no, it is not in relation with the doctrine persistance incompatibility. DoctrineOrmMappingsPass is extended here https://github.com/thephpleague/oauth2-server-bundle/blob/b4a7c22be98e8c03a739dacce1479104fc50dd2a/src/DependencyInjection/CompilerPass/RegisterDoctrineOrmMappingPass.php

**Comment by AurelienPillevesse** [comment]
I have open an issue `doctrine/DoctrineBundle` to know how to fix this : https://github.com/doctrine/DoctrineBundle/issues/1655

**Comment by AurelienPillevesse** [comment]
Fix : https://github.com/thephpleague/oauth2-server-bundle/pull/144

**Comment by maxhelias** [comment]
Hi @sdespont or @chalasr, this issue is fixed you can close it ;)
