### ISSUE TITLE
Abstract scope storage

### ISSUE THREAD

**Issue by ash-m** [thephpleague/oauth2-server-bundle#133]
Currently you must define your scopes in the configuration file you run, however, you may want to associate quite a bit more data with scopes since it is likely you'll want to convey this to the user is a verbose way. For example:
suppose you can `account.interact` as a scope. What does that mean? You might associate: "Interact with other members' photos and videos (comment, add notes, favorite)".

Without abstracting where scopes are defined, you would have to wrap scopes which means you'll have to maintain 2 configurations.

**Comment by chalasr** [comment]
PR welcome to improve the situation.
