### ISSUE TITLE
Incompatible with doctrine/persistence 3.x

### ISSUE THREAD

**Issue by bjo3rnf** [thephpleague/oauth2-server-bundle#135]
Hi,

after running `composer update` on my Symfony 5.4 app I get

```
Context: Using short namespace alias "LeagueOAuth2ServerBundle" by calling Doctrine\ORM\Configuration::addEntityNamespace  
Problem: Feature was deprecated in doctrine/persistence 2.x and is not supported by installed doctrine/persistence:3.x     
Solution: See the doctrine/deprecations logs for new alternative approaches. 
```

Is there anything I can do on my side except for downgrading doctrine/persistence to 2.5.7 (the last 2.x version I think)?

Thanks a lot for your help.

Cheers
Björn

PS: Same goes for a fresh install in Symfony 6.2

**Comment by bjo3rnf** [comment]
It seems that removing the registration of aliases in `RegisterDoctrineOrmMappingPass` is sufficient since FQNs are already used in queries.

**Comment by sdespont** [comment]
After testing, it is working if you don't install the last doctrine ORM 2.14.2 release 2023-04-12 

Use "doctrine/orm": "2.14.1" in composer

But I don't unserstand which part of the change is rising the error : https://github.com/thephpleague/oauth2-server-bundle/issues/135

**Comment by bjo3rnf** [comment]
It's https://github.com/thephpleague/oauth2-server-bundle/blob/ff14fe05f0910015739147750ab0f1ecb75de2e4/src/DependencyInjection/CompilerPass/RegisterDoctrineOrmMappingPass.php#L23 that's causing the issue. Registering of Aliases is deprecated and IMHO this can safely be removed.

**Comment by bobvandevijver** [comment]
@bjo3rnf is correct. [This is the pull request](https://github.com/doctrine/orm/pull/10489) that introduced the missing throw, which should have been there for quite some time already.

I believe the line can indeed be removed safely. See #137 for the PR to fix this.

**Comment by sdespont** [comment]
@chalasr Thank you very much for the merge. Would it be possible to have a new release permitting to avoid the doctrine incompatibility?
