### ISSUE TITLE
No longer able to install with Symfony 6.0 and 6.1 since #127, however documentation mention it is still supported

### ISSUE THREAD

**Issue by paul999** [thephpleague/oauth2-server-bundle#139]
Hi,
Since the changes in #127 it requires Symfony 5.4 or 6.2 (Which seems only being done because Symfony 6.0/6.1 is no longer supported), however the documentation still mention it is supported on Symfony 5.4 and higher.

While I understand that Symfony is no longer supported, it seems there is no other reason. Would it be possible (Especially because of #135 ), to have a release that includes the fix for #135, but is still supporting Symfony 6.0/6.1.

Or, otherwise at least update the documentation that Symfony 6.0/6.1 is no longer supported?

**Comment by chalasr** [comment]
Sorry for the super late feedback. As long as the bundle is is 0.x version, we allow ourselves to only supported the last stable version of our vendors, Symfony included.
PR welcome to update the supported versions in the docs.
