### ISSUE TITLE
use http foundation response in `AuthorizationRequestResolveEvent`.

### ISSUE THREAD

**Issue by azjezz** [thephpleague/oauth2-server-bundle#14]
currently, `AuthorizationRequestResolveEvent::setResponse` uses PSR 7 response, later this response gets converted to a symfony response.

https://github.com/thephpleague/oauth2-server-bundle/blob/93c407821c8a025b73f5028c21c7e9e4cb4d63bd/src/Controller/AuthorizationController.php#L101-L114

since this event is part of the bundle, and most symfony applications use http foundation rather than PSR 7, it makes sense to default to Http Foundation rather than PSR 7.

**Comment by chalasr** [comment]
I agree 👍
