### ISSUE TITLE
Better checks for access rights

### ISSUE THREAD

**Issue by AurelienPillevesse** [thephpleague/oauth2-server-bundle#142]
Instead of using a listener `CheckScopeListener` (https://github.com/thephpleague/oauth2-server-bundle/blob/60e209852edafccacb3ab43b406d8288a84b2c7f/src/Security/EventListener/CheckScopeListener.php)

Is it a good idea to transform it into a Symfony Voter ? It will improve performances with the Symfony cache.

What do you think about it ?

**Comment by chalasr** [comment]
PR welcome to give it a try.
