### ISSUE TITLE
Constructor in AbstractClient class

### ISSUE THREAD

**Issue by xergio** [thephpleague/oauth2-server-bundle#146]
Hi.

AbstractClient constructor should be removed. It causes a lot of problems not following the good practices, for example with Symfony Forms, EasyAdmin and ApiPlatform.

All this packages try to instantiate the object and fails because the arguments.

In addition we cant extend this class to create methods like setSecret (for example) because the property is private, and there is no setter for this prop.

**Comment by alexsegura** [comment]
+1 

I would like to allow changing the secret of an existing client, and it's not possible.

**Comment by chalasr** [comment]
Would you like to submit a PR?

**Comment by chalasr** [comment]
PR welcome if you think you can do something to improve the situation. Thanks
