### ISSUE TITLE
0.5.0 with php 8.2, Symfony 6.2, doctrine/persistence 3.x, doctrine/orm 2.15.x

### ISSUE THREAD

**Issue by tskorupka** [thephpleague/oauth2-server-bundle#148]
Hello,

prerequisites

- `"league/oauth2-server-bundle": "^0.5"`
- `"symfony/*": "6.2.*"`
- `"doctrine/persistence": "^3.1"`
- `"doctrine/orm": "^2.15"`

during `composer update`

```
Context: Using short namespace alias "LeagueOAuth2ServerBundle" by calling   
!!    Doctrine\ORM\Configuration::addEntityNamespace                               
!!    Problem: Feature was deprecated in doctrine/persistence 2.x and is not supp  
!!    orted by installed doctrine/persistence:3.x                                  
!!    Solution: See the doctrine/deprecations logs for new alternative approaches  
!!    .
```

**Comment by tskorupka** [comment]
#135 does not fix this

**Comment by chalasr** [comment]
Up for a PR?

**Comment by X-Coder264** [comment]
Are you sure that you are using v0.5.0 because the `LeagueOAuth2ServerBundle` short alias registration was removed in https://github.com/thephpleague/oauth2-server-bundle/pull/136 ?

**Comment by tskorupka** [comment]
Hi, I am sorry, what I have done, is that I had been upgraded `doctrine/orm` to `2.15` during upgrading also `league/oauth2-server-bundle` to `0.5`, and I was given an error.

I tried to check to confirm @X-Coder264 that if I was using `league/oauth2-server-bundle:0.5`, and I was, so I tried again to bump `doctrine/orm` to `2.15` from `2.14` and it succeeded, that is a weird, maybe I just missed that, sorry.
