### ISSUE TITLE
League\\Bundle\\OAuth2ServerBundle\\Security\\User\\NullUser was not found in the chain configured namespaces

### ISSUE THREAD

**Issue by facundososalopez** [thephpleague/oauth2-server-bundle#156]
I have this error:

The class 'League\\Bundle\\OAuth2ServerBundle\\Security\\User\\NullUser' was not found in the chain configured namespaces App\\Entity\\Main, League\\Bundle\\OAuth2ServerBundle\\Model

I don't know the reason why this occurs.

Only happens on entity persist

**Comment by facundososalopez** [comment]
I just realized that the error occurs because the I'm using blameable extension of StofDoctrineExtensionsBundle.

**Comment by olivier1980** [comment]
@facundososalopez I have the same issue, can you explain why the StofDoctrineExtensionsBundle is the problem and how did you fix it?
