### ISSUE TITLE
Symfony 6.3 compatibility (symfony/psr-http-message-bridge)

### ISSUE THREAD

**Issue by maisoui** [thephpleague/oauth2-server-bundle#158]
Hi,

I have composer error with Symfony 6.3 about "**symfony/psr-http-message-bridge**":

`league/oauth2-server-bundle[v0.1.0, ..., v0.1.2] require symfony/framework-bundle ^5.3 -> found symfony/framework-bundle[v5.3.0-BETA1, ..., 5.4.x-dev] but it conflicts with your root composer.json require (^6.0).`

`league/oauth2-server-bundle[dev-master, v0.2.0, ..., v0.5.0] require symfony/psr-http-message-bridge ^2.0 -> found symfony/psr-http-message-bridge[v2.0.0, ..., 2.3.x-dev] but these were not loaded, likely because it conflicts with another require.`

`Root composer.json requires league/oauth2-server-bundle * -> satisfiable by league/oauth2-server-bundle[dev-master, v0.1.0, ..., v0.5.0].`

Best regards

**Comment by yvalentin** [comment]
@maisoui You can add `"symfony/psr-http-message-bridge": "^2.3"` to the `require` section of your project.

I have check it and it's working

Related to: 
- https://github.com/getsentry/sentry-symfony/issues/749#issuecomment-1658462772
- https://github.com/symfony/symfony/issues/51192
- https://github.com/symfony/symfony/pull/51100

**Comment by maisoui** [comment]
Thank you for your answer. 
I already used this workaround. ;-)
