### ISSUE TITLE
Lack of versionning

### ISSUE THREAD

**Issue by floviolleau** [thephpleague/oauth2-server-bundle#176]
Hi,

Thanks for maintaining this project.

We are lacking of versions of this bundle.
We are on dev-master but now dev-master is php8 only compatible.

Can tell me when was the last version available for php7.4 ?

Thanks

**Comment by X-Coder264** [comment]
The latest tagged version at the moment is 0.5.0 and it supports PHP >= 7.2

https://github.com/thephpleague/oauth2-server-bundle/blob/v0.5.0/composer.json#L19

Why are you using `dev-master` instead of the latest tag?

**Comment by floviolleau** [comment]
Hi,

My mistake, I think I misread. 

We were on dev-master for an old reason.

Sorry for the noise.
