### ISSUE TITLE
A logged in user is required to resolve the authorization request.

### ISSUE THREAD

**Issue by ro0NL** [thephpleague/oauth2-server-bundle#200]
Hi,

After bumping v0.8.0 to v0.9.0, we see sporadically `A logged in user is required to resolve the authorization request.` in prod.

Im wondering if it's a tampered/invalid call, and thus the controller should produce 4xx instead.

**Comment by krkabol** [comment]
Please see docs  https://github.com/thephpleague/oauth2-server-bundle/blob/44272ff229da25305d4f5612546851bbcaa72d9a/docs/index.md?plain=1#L149 - it is required to set it after Flex manually


similar to #191

**Comment by ro0NL** [comment]
oh wow, it was indeed missing in one of our apps :cold_sweat: 

thanks!
