### ISSUE TITLE
make the default scope(s) configurable

### ISSUE THREAD

**Issue by azjezz** [thephpleague/oauth2-server-bundle#22]
currently, creating a client with no scopes, gives the client access to all the scopes, which is a bad idea in most cases, since the user might forget to specify them when creating a client, resulting in a security vulnerability. 

we need to have an event listener that adds default scopes before the client is persisted if the client doesn't have any.

**Comment by chalasr** [comment]
100% agree.

**Comment by azjezz** [comment]
+ the configuration entry should be required, not optional.

**Comment by azjezz** [comment]
we should also mention in the docs that if you want a client with access to everything, you can have a scope for it, and configure that scope in the role_hierarchy to have access to everything you want.

e.g:

```
    'role_hierarchy' => [
        'OAUTH_SCOPE_SUPER_CLIENT' => [
            'OAUTH_SCOPE_EMAIL',
            'OAUTH_SCOPE_PREFERENCES',
            ... etc
        ],
    ],
```
