### ISSUE TITLE
Authenticated `NullUser`

### ISSUE THREAD

**Issue by mtarld** [thephpleague/oauth2-server-bundle#34]
One thing I'm really unsure about is the `NullUser`. 
I know it has been borrowed from trikoder's guard authenticator, but I'm pretty sure such object should never end up in the token storage as part of an authenticated token. 
I think the `userLoader` callable passed to the UserBadge should just return null when it has no valid identifier, letting the UserBadge throw an AuthenticationException. I may miss some cases where we don't want such exception to be thrown, but having an authenticated NullUser in the storage feels wrong anyway.

Apart from that, this is awesome. Really nice work.
Merging now so that we can move forward and iterate.

_Originally posted by @chalasr in https://github.com/thephpleague/oauth2-server-bundle/issues/24#issuecomment-832616390_

**Comment by X-Coder264** [comment]
The only reason we've added `NullUser` in the first place is because `\Symfony\Component\Security\Guard\AuthenticatorInterface::getUser` method requires that a `UserInterface` instance gets returned. As we wanted to support the client credentials grant via the guard we added the `NullUser` class. If the new authenticator system does not have such a limitation then the `NullUser` class can indeed be deleted.

**Comment by mtarld** [comment]
Unfortunately, the `UserBadge` seems to need to return an `UserInterface`. For intstance:
```php
    // Symfony\Component\Security\Http\Authenticator\Passport\Badge\UserBadge:59

    /**
     * @throws AuthenticationException when the user cannot be found
     */
    public function getUser(): UserInterface
    {
        if (null === $this->user) {
            if (null === $this->userLoader) {
                throw new \LogicException(sprintf('No user loader is configured, did you forget to register the "%s" listener?', UserProviderListener::class));
            }

            $this->user = ($this->userLoader)($this->userIdentifier);
            if (!$this->user instanceof UserInterface) {
                throw new UsernameNotFoundException();
            }
        }

        return $this->user;
    }

```

That's why I followed that approach

**Comment by chalasr** [comment]
Thanks both, your explanations make sense. Closing here
