### ISSUE TITLE
delegate league events to symfony

### ISSUE THREAD

**Issue by azjezz** [thephpleague/oauth2-server-bundle#35]
League oauth server dispatches multiple events during the process of authenticating clients .. etc, however, symfony users are not able to make use of these events since they are not dispatched from the symfony event dispatcher.

I propose that we create a set of event listeners that will be dispatched by the league event dispatcher, and be used to delegate the events to symfony.

**Comment by ostiwe** [comment]
Do you think there is any progress on this issue? Or did everyone give up on it?

**Comment by chalasr** [comment]
AFAIK No one worked on this yet

**Comment by X-Coder264** [comment]
I've just sent in https://github.com/thephpleague/oauth2-server-bundle/pull/65 to address this feature request.
