### ISSUE TITLE
When are you going to release the stable version of the bundle?

### ISSUE THREAD

**Issue by Kravalg** [thephpleague/oauth2-server-bundle#36]
I understand that the tricorder repository is abandoned and this one will replace it. 
We have implemented it in our project and would like to know when this bundle will be released,
what plans are there for it in the future.

You are doing a great job, guys 
Thanks in advance for your answer

**Comment by NicoHaase** [comment]
@chalasr any news on this? In #1, you've mentioned that July would be a good release date - but in which year? ;)

**Comment by chalasr** [comment]
Hey,

I'm very sorry about the lack of advancement on this new project. 
We've been really busy working on existing projects for the past year, notably rewriting Symfony core's security integration. 
The good news is that the work done mentioned above provides us way better foundations for this new bundle. 
We took over the WIP recently and did some big changes already. This is in active development, we will manage to have a first release for the beginning of this summer (2021 😉).

Thanks for your interest, that's the best source of motivation for us.

**Comment by chalasr** [comment]
I'm going to release a first 1.0-beta version in 2 weeks. 
Early feedbacks are more than welcome meanwhile :)

**Comment by Kravalg** [comment]
Hi there
How it's going on?

**Comment by chalasr** [comment]
Here is the first release: https://github.com/thephpleague/oauth2-server-bundle/releases/tag/v0.1.0
> This bundle is ready for production, but breaking changes may happen in next releases until a v1.0.0 tag is released.
We'll try to avoid BC breaks as possible though, only if required for adding new features. 

The main goals for next releases are the following:
- Better developer experience (including a Flex recipe, improved configuration/public API, complete documentation)
- Full OpenID Connect (OIDC) support

**Comment by Kravalg** [comment]
Thanks for your work!
Looking forward to new releases 🥳

**Comment by chalasr** [comment]
Thanks a lot for your enthusiasm and for using this bundle. 
We are looking for feedbacks and suggestions to make it the best OAuth integration out there :)

**Comment by chalasr** [comment]
I think we can close here.
