### ISSUE TITLE
Unrecognized option "connections" under "doctrine.dbal.connections.default" after composer update

### ISSUE THREAD

**Issue by maisoui** [thephpleague/oauth2-server-bundle#38]
Hi,

There is an issue after upgrading to latest version of Doctrine bundle. I guess, this is the same problem as Trikoder oauth2 package :
https://github.com/trikoder/oauth2-bundle/issues/279

The option "'connections' => null," needs to be removed in Dependency Injection.

Best regards

**Comment by chalasr** [comment]
Issue was on doctrine's side, it's been fixed now.
