### ISSUE TITLE
Is this fork dead or not ?

### ISSUE THREAD

**Issue by jr-k** [thephpleague/oauth2-server-bundle#40]
"Fork of trikoder/oauth2-bundle, for the better."

There are 4 tiny pull requests, if you are too busy let me know, I can handle that kind of repository as a maintainer. I don't wanna fork a fork...

Thanks.

**Comment by chalasr** [comment]
It is not dead, but not stable yet. I'm going to spend most of July to move it forward. 
Be patient, please. 
Meanwhile, early feedback and pull requests are welcome.
Thanks for your understanding.
