### ISSUE TITLE
Support for anonymous users

### ISSUE THREAD

**Issue by KorvinSzanto** [thephpleague/oauth2-server-bundle#42]
Right now the included `BearerTokenValidator` throws `OAuthServerException`s if a bearer token isn't passed. This makes it impossible to implement anonymous user support and leads to plaintext output of `The resource server rejected the request.`. It'd be better if there were support for anonymous users as scopes / roles are an adequate way to gate access rather than requiring a user always be logged in.

My specific use case for this is OAuth2 to gate access to a graphql api. I want the graphql api to always be available while access to specific items requires a logged in user and the appropriate roles. This way tools can access the graphql schema without needing a valid JWT.

**Comment by chalasr** [comment]
Fixed in #43. Thanks for the report
