### ISSUE TITLE
Something wrong with config?

### ISSUE THREAD

**Issue by yaroslavhoisa** [thephpleague/oauth2-server-bundle#5]
![image](https://user-images.githubusercontent.com/6161950/100891014-833bd100-34c1-11eb-88fe-16a13c7b26ca.png)
 but config is already there
![image](https://user-images.githubusercontent.com/6161950/100891116-9e0e4580-34c1-11eb-807b-d5c08b06fa6a.png)

"symfony/framework-bundle": "5.2.*",

**Comment by yaroslavhoisa** [comment]
misspelled a file extension .yAml ....

**Comment by chalasr** [comment]
Thanks for being an early adopter @yaroslavhoisa :)
