### ISSUE TITLE
How is client credentials grant supposed to work without knowledge of who is logged in?

### ISSUE THREAD

**Issue by Tetragramat** [thephpleague/oauth2-server-bundle#50]
How is client credentials grant supposed to work without knowledge of who is logged in?
Currently using trikoder version of bundle, but this one seems to have the same issue.
When I log in using client credentials grant, then I'm logged in as NullUser with no knowledge as which Client I'm.
Might be usefull if Token/Passport contained at least client_id.

**Comment by chalasr** [comment]
Makes sense, yes. Are you up for a PR?

**Comment by Tetragramat** [comment]
Sorry, I don't have enought free time. I can at least make issues about problems I found while using it.

**Comment by chalasr** [comment]
No problem, thanks for the report.

**Comment by X-Coder264** [comment]
@chalasr This issue can now be closed as it was addressed by https://github.com/thephpleague/oauth2-server-bundle/pull/60
