### ISSUE TITLE
Is there going to be a release any time soon?

### ISSUE THREAD

**Issue by jasonpeltzer** [thephpleague/oauth2-server-bundle#84]
It seems like there are many issues trying to move towards Symfony 5.4/6.0.  Just wondering as this is an active blocker for doing the upgrades, I can only make v0.1.2 work, attempting to upgrade has been a fruitless effort.

**Comment by jasonpeltzer** [comment]
https://github.com/thephpleague/oauth2-server-bundle/issues/77

**Comment by Tetragramat** [comment]
There are no pull requests and no new commits since last release, so there is no reason to make new release. If you have time then make PR.

**Comment by chalasr** [comment]
Closing in favor of #77 where the original discussion is. Thanlks
